### ISSUE TITLE
Is there any way to Remove state of the WorkFlow on Workflow completion from persistence storage?

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#376] opened 2019-08-29 11:42 UTC
I have been looking to clear a workflow state from the persistence storage on workflow completion.
so is any method available?

**Comment by ssougnez** [comment] 2019-08-29 15:52
By workflow state, you mean the data used to start the workflow ? If so, to do it, I just wrote a simple step that put `context.Workflow.Data` to `null` ;-)

**Comment by danielgerlag** [comment] 2019-09-02 14:47
duplicate of #368

**Closed by danielgerlag** 2019-09-02 14:47 UTC
Labels: duplicate

**Comment by Reena-Patel** [comment] 2019-10-09 13:32
Would it be possible to purge the data from Redis persistence storage?

**Comment by Reena-Patel** [comment] 2019-11-25 11:27
@danielgerlag is you can please provide thoughts on my above [comment](https://github.com/danielgerlag/workflow-core/issues/376#issuecomment-540002266)

**Comment by danielgerlag** [comment] 2019-11-30 18:03
We created a purge method - https://github.com/danielgerlag/workflow-core/releases/tag/2.1.2
Still need to do the redis provider implementation.

**Comment by Reena-Patel** [comment] 2019-12-03 06:51
@danielgerlag Thanks for the update. Can you please let us know when that method will be implemented for Redis?

**Comment by danielgerlag** [comment] 2019-12-05 03:02
I don't currently have any short term plans for this... but I am getting a GitHub sponsors account setup and I will prioritize sponsors features.

**Comment by Reena-Patel** [comment] 2019-12-05 05:21
@danielgerlag Thanks for the update. Can you please help us to write a code to clear the redis cache for the completed workflow.
Concrete implementation of the IWorkflowPurger for Redis.

**Comment by Reena-Patel** [comment] 2019-12-10 13:21
Hi, @danielgerlag 

- Here I have attached source code for the concrete implementation IWorkflowPurger for Redis persistence provider. Can you please review and suggest if any changes are required.

```
public class WorkflowPurger : IWorkflowPurger
    {
        private readonly string _connectionString;
        private readonly string _prefix;
        private const string WORKFLOW_SET = "workflows";
        private readonly IConnectionMultiplexer _multiplexer;
        private readonly IDatabase _redis;
        
        public WorkflowPurger(string connectionString, string prefix)
        {
            _connectionString = connectionString;
            _prefix = prefix;
            _multiplexer = ConnectionMultiplexer.Connect(_connectionString);
            _redis = _multiplexer.GetDatabase();
        }
        public async Task PurgeWorkflows(WorkflowStatus status, DateTime olderThan)
        {
            var result = _redis.HashScan($"{_prefix}.{WORKFLOW_SET}").
                            Select(he => JsonConvert.DeserializeObject<WorkflowInstance>(he.Value)).ToList();

            var selectedWorkflows = result.Where(a => a.Status == status && a.CompleteTime < olderThan).ToList();

            var hashFields = Array.ConvertAll(selectedWorkflows.Select(a => a.Id).ToArray(), x => (RedisValue)x);

            await _redis.HashDeleteAsync($"{_prefix}.{WORKFLOW_SET}", hashFields: hashFields);
        }
    }
```

- Here I am attaching an code were on creating an event some data is added in redis but at the time mark it as processed that data is not removed from the Redis. Do you think we should add commented code in the method 'MarkEventProcessed' of RedisPersistenceProvider.
```
 public async Task<string> CreateEvent(Event newEvent)
        {
            newEvent.Id = Guid.NewGuid().ToString();
            var str = JsonConvert.SerializeObject(newEvent, _serializerSettings);
            **await _redis.HashSetAsync($"{_prefix}.{EVENT_SET}", newEvent.Id, str);**
            **await _redis.SortedSetAddAsync($"{_prefix}.{EVENT_SET}.{EVENTSLUG_INDEX}.{newEvent.EventName}-{newEvent.EventKey}", newEvent.Id, newEvent.EventTime.Ticks);**

            if (newEvent.IsProcessed)
                await _redis.SortedSetRemoveAsync($"{_prefix}.{EVENT_SET}.{RUNNABLE_INDEX}", newEvent.Id);
            else
                await _redis.SortedSetAddAsync($"{_prefix}.{EVENT_SET}.{RUNNABLE_INDEX}", newEvent.Id, newEvent.EventTime.Ticks);

            return newEvent.Id;
        }
        public async Task MarkEventProcessed(string id)
        {
            var evt = await GetEvent(id);
            evt.IsProcessed = true;
            var str = JsonConvert.SerializeObject(evt, _serializerSettings);
            await _redis.HashSetAsync($"{_prefix}.{EVENT_SET}", evt.Id, str);
            **//await _redis.HashDeleteAsync($"{_prefix}.{EVENT_SET}", evt.Id);**
            await _redis.SortedSetRemoveAsync($"{_prefix}.{EVENT_SET}.{RUNNABLE_INDEX}", id);
            **//await _redis.SortedSetRemoveAsync($"{_prefix}.{EVENT_SET}.{EVENTSLUG_INDEX}.{evt.EventName}-{evt.EventKey}", id);**
        }
```

**Comment by Reena-Patel** [comment] 2019-12-12 04:47
Hello @danielgerlag If you can please review my above comment.

I have also found that if parallelly we wait for 2 events and if one event received then second event processing will not be executed. In such case subscription related cache for second event does not removed from the cache.

```.Parallel()
                        .Do(FileUploadedToFrostBankWaitEvent => FileUploadedToFrostBankWaitEvent
                            .StartWith(step => ExecutionResult.Next())
                            .WaitFor(WorkflowEvents.FileUploadedToFrostBank.ToString(), eventKey => eventKey.CorrelationId, null, context => (context.IsPositivePayFileUploaded.HasValue && !context.IsPositivePayFileUploaded.Value))
                            .Output(context => context.IsPositivePayFileUploaded, IsPositivePayFileUploaded => true)
                            .Then<DeletePositivePayFile>()
                            .Then<TrackCheckPaymentPositivePayDetail>()
                            .Then<PublishPayoutCreatedEvent>()
                        )
                        .Do(UploadFileToFrostBankFailedWaitEvent => UploadFileToFrostBankFailedWaitEvent.
                            StartWith(step => ExecutionResult.Next())
                            .WaitFor(WorkflowEvents.UploadFileToFrostBankFailed.ToString(), eventKey => eventKey.CorrelationId, null, context => (context.IsPositivePayFileUploaded.HasValue && context.IsPositivePayFileUploaded.Value))
                            .Output(d3 => d3.IsPositivePayFileUploaded, IsPositivePayFileUploaded => false)
                            .Output(context => context.ErrorCode, step => ((UploadFileToFrostBankFailedEventDataContext)step.EventData).ErrorCode)
                            .Then<DeletePositivePayFile>()
                            .Then<PublishPayoutCreationFailedEvent>()
                        )```
Below keys remains in the cache.
1) "FinanceServiceWorkflow.subscriptions.eventslug.BankTransferPayoutFileCreationFailed-45fg5lvgfghfj6565"
2) "FinanceServiceWorkflow.subscriptions.eventslug.UploadFileToFrostBankFailed-45fg5lvgfghfj6565"
3) "FinanceServiceWorkflow.subscriptions"
